version: "3.9"

services:
  db:
    image: postgres:14
    restart: always
    container_name: wishlify-db
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data

  backend:
    build: ./server
    restart: always
    ports:
      - 5000:5000
    container_name: wishlify-backend
    env_file:
      - .env
    depends_on:
      - db
