name: CI

on:
  pull_request:

jobs:
  CI:
    runs-on: ubuntu-latest
    defaults:
      working-directory: server
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.19"
      - name: Install dependencies
        run: go mod download && go mod verify
      - name: Test
        run: go test -v ./...
      - name: Build
        run: go build -v .
