name: CI backend

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
  pull_request:
    paths:
      - "server/**"

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.19"
      - name: Install dependencies
        working-directory: server
        run: go mod download && go mod verify
      - name: Test
        working-directory: server
        run: go test -v ./...
      - name: Build
        working-directory: server
        run: go build -v .
