name: CI web

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
  pull_request:
    paths:
      - "web/**"

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        working-directory: web
        run: npm ci
      - name: Check formatting
        working-directory: web
        run: npx prettier -c .
      - name: Lint
        working-directory: web
        run: npm run lint
      - name: Build
        working-directory: web
        run: npm run build
